redis:
  enabled: false
  host: localhost
  port: 6379
  ssl: false
  database: 0
  user:
  password:
givecreativeplot:
  max-plots: 9
  min-plots: 4
extras:
  skincontrol: true
  delayedcommands: true
  tempflyvouchers: true
  tfcommand: "tf give {player} 45m"
