name: "MythicStore"
version: "1.1.0"
description: "Utilities to help mythicmc/store run actions on the MythicMC server."
authors: ["Ibrahim Ansari <ansari.ibrahim1@gmail.com>"]
main: "org.mythicmc.mythicstore.MythicStore"
api-version: "1.13"

commands:
  mythicstore:
    description: "Reloads MythicStore config."
    usage: "§cRun /mythicstore reload to reload the plugin."
    permission: mythicstore.reload
  givecreativeplot:
    description: "Gives the player an additional creative plot."
    usage: "/givecreativeplot <player>"
    permission: mythicstore.giveplot

permissions:
  mythicstore.reload:
    description: "Reload MythicStore config."
    default: op
  mythicstore.giveplot:
    description: "Give a player a plot"
    default: op